# Generated by Django 3.2.8 on 2021-10-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Question1',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='question1',
            old_name='question_text',
            new_name='question1_text',
        ),
    ]
